name: Build LaTeX document
on:
  - push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          args: "-usepretex=\\def\\outputlangen{1}\\def\\outputlanges{1}"
          root_file: cv.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: cv altoe francisco (en+es).pdf
          path: cv.pdf
