name: Build LaTeX document
on:
  - push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output-lang: [en, es, en+es]
        include:
          - output-lang: en
            outputlanges: ""
            outputlangen: "1"
          - output-lang: es
            outputlanges: "1"
            outputlangen: ""
          - output-lang: en+es
            outputlanges: "1"
            outputlangen: "1"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_lualatex: true
          args: -usepretex=\def\outputlangen{${{ matrix.outputlangen }}}\def\outputlanges{${{ matrix.outputlanges }}} -jobname=cv_altoe_francisco_(${{ matrix.output-lang }})
          root_file: cv.tex
      - name: Upload PDF files
        uses: actions/upload-artifact@v3
        with:
          name: cv_altoe_francisco
          path: cv_altoe_francisco_(${{ matrix.output-lang}}).pdf

  publish_pdf:
    needs:
      - build_latex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cv_altoe_francisco
      - name: Set release name
        id: release-setter
        run: |
          echo RELEASE_TITLE=$(date '+%Y-%m-%d %H:%M:%S') >> $GITHUB_OUTPUT
          echo RELEASE_TAG=$(date '+%Y%m%dT%H%M%S') >> $GITHUB_OUTPUT
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.REPO_ACCESS_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          title: ${{ steps.release-setter.output.RELEASE_TITLE }}
          files: |
            *.pdf
